apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-11-08T14:56:46Z","generation":2,"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"191093","uid":"532d7d94-1006-4216-b7dc-207b03f48196"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"currency-exchange"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"currency-exchange"}},"spec":{"containers":[{"image":"chaklader/mmv2-currency-exchange-service:0.0.11-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"mmv2-currency-exchange-service","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2021-11-08T14:56:46Z","lastUpdateTime":"2021-11-08T14:57:00Z","message":"ReplicaSet \"currency-exchange-cd8b54dbb\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2021-11-08T16:56:18Z","lastUpdateTime":"2021-11-08T16:56:18Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":2,"replicas":2,"unavailableReplicas":2,"updatedReplicas":2}}
  creationTimestamp: "2021-11-08T14:56:46Z"
  generation: 3
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "192193"
  uid: 532d7d94-1006-4216-b7dc-207b03f48196
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: chaklader/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-exchange-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-11-08T14:56:46Z"
    lastUpdateTime: "2021-11-08T14:57:00Z"
    message: ReplicaSet "currency-exchange-cd8b54dbb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-08T16:56:18Z"
    lastUpdateTime: "2021-11-08T16:56:18Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 3
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}"},"creationTimestamp":"2021-11-08T14:57:06Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"currency-exchange"},"name":"currency-exchange","namespace":"default","resourceVersion":"187184","uid":"9c294a12-8d6d-4bad-ba67-82a32652d9bc"},"spec":{"clusterIP":"10.12.13.139","clusterIPs":["10.12.13.139"],"externalTrafficPolicy":"Cluster","ports":[{"nodePort":32635,"port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"currency-exchange"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"23.236.61.156"}]}}}
  creationTimestamp: "2021-11-08T14:57:06Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "191814"
  uid: 9c294a12-8d6d-4bad-ba67-82a32652d9bc
spec:
  clusterIP: 10.12.13.139
  clusterIPs:
    - 10.12.13.139
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32635
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 23.236.61.156
